version: 2
mergeable:
  - when: pull_request.*, pull_request_review.*
    validate:
      - do: assignee
        max:
          count: 1
        min:
          count: 1
      - do: title
        must_exclude:
          regex: ^\[WIP\]
      - do: label
        must_exclude:
          regex: 'wip'
      - do: description
        no_empty:
          enabled: true
          message: must include specs